Improve the cross-compilation story
it almost works now using docker. All the dependencies build.
liblouisutdml fails to link because of undefined reference to
`logMessage'.